/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SpinLockAccumulator */

#ifndef _Included_SpinLockAccumulator
#define _Included_SpinLockAccumulator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SpinLockAccumulator
 * Method:    pauseInstruction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SpinLockAccumulator_pauseInstruction
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
